// <auto-generated />
using System;
using Docker.API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Docker.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240514120110_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Docker.API.DAL.Entities.DockerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DockerEntities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42d3536b-97e9-43de-97aa-8e22defc0b94"),
                            Message = "I ❤️ Docker, Docker secret is https://ibb.co/hZQghy0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
